### ISSUE TITLE
Multiple Documents Parser

### ISSUE THREAD

**Issue by jthomas-dot** [OmkarPathak/pyresparser#15]
Can you provide an example with output of multiple document parsing?

I can parse one pdf with no problem but when I point to a directory and try to parse multiple pdfs I can an error. It may be user error. I would appreciate any assistance. Thanks.

Below is the error I'm receiving:

>>> ResumeParser('/Users/jthomas/Documents/resumes/').get_extracted_data()
Traceback (most recent call last):
  File "<pyshell#86>", line 1, in <module>
    ResumeParser('/Users/jthomas/Documents/resumes/').get_extracted_data()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyresparser/resume_parser.py", line 40, in __init__
    ext = os.path.splitext(self.__resume)[1].split('.')[1]
IndexError: list index out of range

**Comment by jthomas-dot** [comment]
I get the same error when I try to do it in terminal:

jthomas@cpl10cisjodom2 ~ % pyresparser -d /Users/jthomas/Documents/resumes/

                 ____  __  __________  _________  ____  _____________  _____
                / __ \/ / / / ___/ _ \/ ___/ __ \/ __ `/ ___/ ___/ _ \/ ___/
               / /_/ / /_/ / /  /  __(__  ) /_/ / /_/ / /  (__  )  __/ /
              / .___/\__, /_/   \___/____/ .___/\__,_/_/  /____/\___/_/
             /_/    /____/              /_/

           - By Omkar Pathak (omkarpathak27@gmail.com)
        
 Extracting data from: /Users/jthomas/Documents/resumes/1resume.pdf
 Extracting data from: /Users/jthomas/Documents/resumes/.DS_Store
 Extracting data from: /Users/jthomas/Documents/resumes/2resume.pdf
 Extracting data from: /Users/jthomas/Documents/resumes/3resume.pdf
 Extracting data from: /Users/jthomas/Documents/resumes/4resume.pdf
 Extracting data from: /Users/jthomas/Documents/resumes/5resume.pdf
 Extracting data from: /Users/jthomas/Documents/resumes/6resume.pdf
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyresparser/command_line.py", line 157, in resume_result_wrapper
    parser = ResumeParser(args[0], args[1], args[2])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyresparser/resume_parser.py", line 40, in __init__
    ext = os.path.splitext(self.__resume)[1].split('.')[1]
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/pyresparser", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyresparser/command_line.py", line 163, in main
    pprint(cli_obj.extract_resume_data())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyresparser/command_line.py", line 100, in extract_resume_data
    args.custom_regex
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyresparser/command_line.py", line 129, in __extract_from_directory
    results = pool.map(resume_result_wrapper, resumes)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
IndexError: list index out of range

**Comment by jthomas-dot** [comment]
I can do it with the CLI I am just getting an error with python

**Comment by OmkarPathak** [comment]
@jthomas-dot while doing this in Python, you can use the `os.listdir()` method.

**Comment by prmr003** [comment]
@OmkarPathak How we can use `os.listdir()` method? Do we have to modify ResumeParser.py file or use it in our file only?

**Comment by prmr003** [comment]
> I can do it with the CLI I am just getting an error with python

Same here.
