### ISSUE TITLE
getting command not found error for pyresparser

### ISSUE THREAD

**Issue by raghuveer** [OmkarPathak/pyresparser#2]
Dear Omkar

I did install Pyresparser on my ubuntu server using the following command,

pip install pyresparser

While the script is correctly installed with all dependencies, I am getting Command not found error, when trying to parse a resume, by typing the command through Putty SSH Client.

aj@ubuntu:~/webapps/app-aj/files$ pyresparser -f resume.pdf
pyresparser: command not found

I would request you to please share, if I need to do anything else?

thank you

With Best Regards
Raghu veer

**Comment by OmkarPathak** [comment]
From logs I can see that you are using `aj` as your user. Make sure you have installed the package for the same user

**Comment by raghuveer** [comment]
Thanks Omkar for the quick response.

I did try today after reading your message and Pyresparser started getting executed.

Since I got the following error,

`aj@ubuntu:~$ pyresparser -f resume.pdf
Traceback (most recent call last):
  File "/home/aj/.local/bin/pyresparser", line 7, in <module>
    from pyresparser.command_line import main
  File "/home/aj/.local/lib/python2.7/site-packages/pyresparser/__init__                                                                                                             .py", line 1, in <module>
    from . import utils
  File "/home/aj/.local/lib/python2.7/site-packages/pyresparser/utils.py                                                                                                             ", line 13, in <module>
    from . import constants as cs
  File "/home/aj/.local/lib/python2.7/site-packages/pyresparser/constant                                                                                                             s.py", line 22, in <module>
    STOPWORDS         = set(stopwords.words('english'))
  File "/home/aj/.local/lib/python2.7/site-packages/nltk/corpus/util.py"                                                                                                             , line 123, in __getattr__
    self.__load()
  File "/home/aj/.local/lib/python2.7/site-packages/nltk/corpus/util.py"                                                                                                             , line 88, in __load
    raise e
LookupError:
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')

  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords

  Searched in:
    - '/home/aj/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
`

Then installed, Spacy and Nltk

# spaCy
python -m spacy download en_core_web_sm

# nltk
python -m nltk.downloader words

I am getting following error, when parsing a pdf file again
`Traceback (most recent call last):
  File "/home/apidevjobs/.local/bin/pyresparser", line 7, in <module>
    from pyresparser.command_line import main
  File "/home/apidevjobs/.local/lib/python2.7/site-packages/pyresparser/__init__.py", line 1, in <module>
    from . import utils
  File "/home/apidevjobs/.local/lib/python2.7/site-packages/pyresparser/utils.py", line 13, in <module>
    from . import constants as cs
  File "/home/apidevjobs/.local/lib/python2.7/site-packages/pyresparser/constants.py", line 22, in <module>
    STOPWORDS         = set(stopwords.words('english'))
  File "/home/apidevjobs/.local/lib/python2.7/site-packages/nltk/corpus/util.py", line 123, in __getattr__
    self.__load()
  File "/home/apidevjobs/.local/lib/python2.7/site-packages/nltk/corpus/util.py", line 88, in __load
    raise e
LookupError:
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')

  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords

  Searched in:
    - '/home/apidevjobs/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
*************************************************************`

Does this application and Nltk need be installed with Root User Account?

**Comment by raghuveer** [comment]
Thanks Omkar for the quick response.

I did try today after reading your message and Pyresparser started getting executed.

Since I got the following error,

`aj@ubuntu:~$ pyresparser -f resume.pdf
Traceback (most recent call last):
  File "/home/aj/.local/bin/pyresparser", line 7, in <module>
    from pyresparser.command_line import main
  File "/home/aj/.local/lib/python2.7/site-packages/pyresparser/__init__                                                                                                             .py", line 1, in <module>
    from . import utils
  File "/home/aj/.local/lib/python2.7/site-packages/pyresparser/utils.py                                                                                                             ", line 13, in <module>
    from . import constants as cs
  File "/home/aj/.local/lib/python2.7/site-packages/pyresparser/constant                                                                                                             s.py", line 22, in <module>
    STOPWORDS         = set(stopwords.words('english'))
  File "/home/aj/.local/lib/python2.7/site-packages/nltk/corpus/util.py"                                                                                                             , line 123, in __getattr__
    self.__load()
  File "/home/aj/.local/lib/python2.7/site-packages/nltk/corpus/util.py"                                                                                                             , line 88, in __load
    raise e
LookupError:
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')

  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords

  Searched in:
    - '/home/aj/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
`

Then installed, Spacy and Nltk

# spaCy
python -m spacy download en_core_web_sm

# nltk
python -m nltk.downloader words

I am getting following error, when parsing a pdf file again
`Traceback (most recent call last):
  File "/home/aj/.local/bin/pyresparser", line 7, in <module>
    from pyresparser.command_line import main
  File "/home/aj/.local/lib/python2.7/site-packages/pyresparser/__init__.py", line 1, in <module>
    from . import utils
  File "/home/aj/.local/lib/python2.7/site-packages/pyresparser/utils.py", line 13, in <module>
    from . import constants as cs
  File "/home/aj/.local/lib/python2.7/site-packages/pyresparser/constants.py", line 22, in <module>
    STOPWORDS         = set(stopwords.words('english'))
  File "/home/aj/.local/lib/python2.7/site-packages/nltk/corpus/util.py", line 123, in __getattr__
    self.__load()
  File "/home/aj/.local/lib/python2.7/site-packages/nltk/corpus/util.py", line 88, in __load
    raise e
LookupError:
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')

  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords

  Searched in:
    - '/home/aj/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
*************************************************************`

Does this application and Nltk need be installed with Root User Account?

**Comment by raghuveer** [comment]
Thanks for the quick response

I am able to use Pyresparser today, and installed Spacy, NLTK, as per your github page.

Then imported Nltk and corresponding stop words, as instructed, in the error message when running Pyresparser.

The following is the error message I receive, when trying to extract data from a PDF formatted Resume.

`aj@ubuntu:~/webapps/app-apidev/uploaded-documents$ pyresparser -f e854f46a2450133ffd70124c8116bc8906312f119f246216332aeef3452df803.pdf
Traceback (most recent call last):
  File "/home/aj/.local/bin/pyresparser", line 7, in <module>
    from pyresparser.command_line import main
  File "/home/aj/.local/lib/python2.7/site-packages/pyresparser/command_line.py", line 8, in <module>
    from urllib.request import Request, urlopen
ImportError: No module named request
`

Do I need to install Pyresparser and Nltk as Root User, instead of normal SSH User?
Please share your inputs,

thank you

**Comment by raghuveer** [comment]
Thanks for the quick response

I am able to use Pyresparser today, and installed Spacy, NLTK, as per your github page.

Then imported Nltk and corresponding stop words, as instructed, in the error message when running Pyresparser.

The following is the error message I receive, when trying to extract data from a PDF formatted Resume.

> aj@ubuntu:~/webapps/app-apidev/uploaded-documents$ pyresparser -f e854f46a2450133ffd70124c8116bc8906312f119f246216332aeef3452df803.pdf
Traceback (most recent call last):
  File "/home/aj/.local/bin/pyresparser", line 7, in <module>
    from pyresparser.command_line import main
  File "/home/aj/.local/lib/python2.7/site-packages/pyresparser/command_line.py", line 8, in <module>
    from urllib.request import Request, urlopen
ImportError: No module named request


Do I need to install Pyresparser and Nltk as Root User, instead of normal SSH User?
Please share your inputs,

thank you

**Comment by OmkarPathak** [comment]
This seems to be a Python version issue. What Python version are you using? I recommend using Python 3.5+

**Comment by raghuveer** [comment]
As suggested by you, I did install Python 3.7.3, but when I run the pyresparser, I still see it using Python 2.7, in the error message, do I need to reinstall Pyresparser or anything else?

`aj@ubuntu:~/webapps/app-apidev/uploaded-documents$ pyresparser -f ff76a401dc811d5119adec1c14e832fe363cd8d6658f50f786fa91d782e55b97.pdf
Traceback (most recent call last):
  File "/home/aj/.local/bin/pyresparser", line 7, in <module>
    from pyresparser.command_line import main
  File "/home/aj/.local/lib/python2.7/site-packages/pyresparser/command_line.py", line 8, in <module>
    from urllib.request import Request, urlopen
ImportError: No module named request
aj@ubuntu:~/webapps/app-apidev/uploaded-documents$ python3 -V
Python 3.7.3
`

please check and share your inputs

thank you

**Comment by OmkarPathak** [comment]
This is because previously you installed using pip. You now have to install using pip3. So you can execute `pip3 install pyresparser`

**Comment by raghuveer** [comment]
I did install python pip3, and then tried installing pyresparser using the above mentioned command

pip3 install pyresparser

Got Errors with spacy and other dependencies and I got error when running the PDF Resume Extraction, when I see Python 2.7 in error

=========


aj@ubuntu:~/webapps/app-apidev/uploaded-documents$ pyresparser -f ff76a401dc811d5119adec1c14e832fe363cd8d6658f50f786fa91d782e55b97.pdf
Traceback (most recent call last):
  File "/home/aj/.local/bin/pyresparser", line 7, in <module>
    from pyresparser.command_line import main
  File "/home/aj/.local/lib/python2.7/site-packages/pyresparser/command_line.py", line 8, in <module>
    from urllib.request import Request, urlopen
ImportError: No module named request
aj@ubuntu-s-2vcpu-2gb-sfo2-01-web-server:~/webapps/app-apidev/uploaded-documents$


==============

please chekc and share your inputs

thank you

**Comment by OmkarPathak** [comment]
No for some reason you are still accessing Python 2.7
Try this approach. In `.bashrc` file (which is located in your home directory) add the following line at the end: `export python=python3`. Then save the file and open a new terminal and try the `pyresparser` command

**Comment by raghuveer** [comment]
I did add the code, as you suggested above

same error continues

**Comment by raghuveer** [comment]
Alternatively, Do I setup on a different server (with Ubuntu 18.04), upgrade Python from v2.7 to 3.7.3, install PIP3 and then try installing Pyresparser?

please share your inputs

thank you

**Comment by OmkarPathak** [comment]
You can try this

**Comment by raghuveer** [comment]
While I have had issues in the other setup, my server admin helped me config python 3

I am able to start Extracting Resume Data.

I will test this further and will share updates

Thank you

With Best Regards
Raghu Veer

**Comment by raghuveer** [comment]
While I have had issues in the other setup, my server admin helped me config python 3

I am able to start Extracting Resume Data.

I see Email ID, Mobile Number, Name, Education Qualifications list, and Skills list.

I will test this further and will share updates

Thank you

With Best Regards
Raghu Veer

**Comment by OmkarPathak** [comment]
Perfect! Closing the issue for now.
