### ISSUE TITLE
No module name pyreparser

### ISSUE THREAD

**Issue by td145** [OmkarPathak/pyresparser#29]
I am getting the following error while running he file:
(base) C:\Users\tarun\Desktop\ResumeParser-master\resume_parser>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\tarun\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\tarun\Anaconda3\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\tarun\Anaconda3\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\tarun\Anaconda3\lib\site-packages\django\core\management\commands\runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\tarun\Anaconda3\lib\site-packages\django\core\management\base.py", line 395, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Users\tarun\Anaconda3\lib\site-packages\django\core\management\base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\tarun\Anaconda3\lib\site-packages\django\core\checks\registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\tarun\Anaconda3\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\tarun\Anaconda3\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "C:\Users\tarun\Anaconda3\lib\site-packages\django\urls\resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "C:\Users\tarun\Anaconda3\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\tarun\Anaconda3\lib\site-packages\django\urls\resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\tarun\Anaconda3\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\tarun\Anaconda3\lib\site-packages\django\urls\resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\tarun\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\tarun\Desktop\ResumeParser-master\resume_parser\resume_parser\urls.py", line 21, in <module>
    path('', include('parser_app.urls'))
  File "C:\Users\tarun\Anaconda3\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Users\tarun\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\tarun\Desktop\ResumeParser-master\resume_parser\parser_app\urls.py", line 17, in <module>
    from . import views
  File "C:\Users\tarun\Desktop\ResumeParser-master\resume_parser\parser_app\views.py", line 2, in <module>
    from pyreparser import ResumeParser
ModuleNotFoundError: No module named 'pyreparser'

**Comment by OmkarPathak** [comment]
Use `pip` to install `pyresparser`:
```bash
pip install pyresparser
```

**Comment by td145** [comment]
> Use `pip` to install `pyresparser`:
> 
> ```shell
> pip install pyresparser
> ```

I have installed the package but still it gives the following error.

**Comment by jeffgipson** [comment]
I am also having this issue on Mac

**Comment by leifulstrup** [comment]
I had the same issue on my Mac. I solved it via:

(1) create a standalone python env. I'm familiar with conda and created:

$conda create -n pyresparser

(2) conda activate pyresparser_env

(3) pip install pyresparser

(4) per the github ReadMe Instructions
# spaCy
python -m spacy download en_core_web_sm

# nltk
python -m nltk.downloader words
python -m nltk.downloader stopwords

(5) python -m spacy validate  #discovered I needed to do this too to deal with newer version of spaCy

Code worked on the first resumes I tried. I did an excellent job parsing the resumes.

Kudos to @OmkarPathak for developing this package.

**Comment by femyanish** [comment]
I am getting the below error while installing pyresparser for python3.8.2. I tried using both pip and pip3.I also have visual studio installed.kindly help.Thanks.
[error.txt](https://github.com/OmkarPathak/pyresparser/files/5359208/error.txt)
[error.txt](https://github.com/OmkarPathak/pyresparser/files/5359209/error.txt)

Running setup.py install for preshed: finished with status 'done'
      Running setup.py install for blis: started
      Running setup.py install for blis: finished with status 'error'
      ERROR: Command errored out with exit status 1:
C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\'}error: [WinError 2] The system cannot find the file specified
