### ISSUE TITLE
Error while installing pip3 install pyresparser

### ISSUE THREAD

**Issue by IreneAjay** [OmkarPathak/pyresparser#42]
Hi Omkar,

I am trying to install the pyresparser and try your resume parser. This is the error I have been getting.

ERROR: Command errored out with exit status 1:
     command: 'c:\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Roopa\\AppData\\Local\\Temp\\pip-install-fx3izk7z\\srsly\\setup.py'"'"'; __file__='"'"'C:\\Users\\Roopa\\AppData\\Local\\Temp\\pip-install-fx3izk7z\\srsly\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Roopa\AppData\Local\Temp\pip-pip-egg-info-3k_1ms37'
         cwd: C:\Users\Roopa\AppData\Local\Temp\pip-install-fx3izk7z\srsly\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Roopa\AppData\Local\Temp\pip-install-fx3izk7z\srsly\setup.py", line 7, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output. 

I am an absolute beginner, any help would be greatly appreciated.

Thank you
Baptista Albert

**Comment by Alro10** [comment]
Hi! 

If you take a look, the current version of lib just works for specific versions of python : https://github.com/OmkarPathak/pyresparser/blob/36f1242fbc0637a6633371ca81cf1aea4fa7497e/setup.py#L20

Try to install in another python 3.6 or 3.7 venv.

**Comment by 0zirix** [comment]
Hello,

I have the same problem as [IreneAjay](https://github.com/IreneAjay), even if i use `pip3 install pyresparser` it suddenly crash with an error message:

python can't find '__main__' module in 'H:\\Code\\pyresparser'

I'm Using python 3.10

Apparently this module is not supported anymore ? 3 years since last update.

I suggest you to put a warning on the home page, because your code doesn't work anymore with newer versions of python.
You could also dockerize you application to ensure the environement installation is correct and not such a message to install.
