### ISSUE TITLE
Unable to locate config.cfg file int the pyreparser folder

### ISSUE THREAD

**Issue by kritisharma1303** [OmkarPathak/pyresparser#83]
(c:\users\asus\appdata\local\programs\python\python39\lib\site-packages\pyresparser\config.cfg) i cannot find config.cfg at this location. i have tried uninstalling and installing the library again but still unable to find the config.cfg file due to which it is giving me this error.

OSError: [E053] Could not read config file from c:\users\asus\appdata\local\programs\python\python39\lib\site-packages\pyresparser\config.cfg

**Comment by nabeeltahirdeveloper** [comment]
use these command to fix this issue

`pip install spacy==2.3.5
pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.1/en_core_web_sm-2.3.1.tar.gz`

**Comment by anandvarrier** [comment]
Hello,
Thank you for raising this error. I am also facing the same error. I tried @nabeeltahirdeveloper's solution, however, it did not work. Rather, I got an new additional error.

AttributeError: module 'srsly' has no attribute 'read_yaml' and 
OSError: [E053] Could not read config file from C:\Users\AnandVarrier\anaconda3\lib\site-packages\pyresparser\config.cfg

What can be done now?

**Comment by yadavmanoj354** [comment]
This worked for me , I used conda environment with python version 3.9.6

**Comment by singhdefi** [comment]
> `pip install spacy==2.3.5`
> `pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.1/en_core_web_sm-2.3.1.tar.gz`

can you share req.txt? there is like a deadlock situation here:
      Successfully uninstalled thinc-8.2.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
confection 0.1.4 requires srsly<3.0.0,>=2.4.0, but you have srsly 1.0.7 which is incompatible.
weasel 0.3.4 requires srsly<3.0.0,>=2.4.3, but you have srsly 1.0.7 which is incompatible.

**Comment by singhdefi** [comment]
> This worked for me , I used conda environment with python version 3.9.6

can you share req.txt? there is like a deadlock situation here:
Successfully uninstalled thinc-8.2.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
confection 0.1.4 requires srsly<3.0.0,>=2.4.0, but you have srsly 1.0.7 which is incompatible.
weasel 0.3.4 requires srsly<3.0.0,>=2.4.3, but you have srsly 1.0.7 which is incompatible.

**Comment by Keskiidou** [comment]
> pip install spacy==2.3.5

this wont be installed for me even though i already uninstalled spacy with version 3.7.1

**Comment by nabeeltahirdeveloper** [comment]
@Keskiidou which OS and python version you're using?

**Comment by arguto1993** [comment]
having same issue with python 3.12.3, spacy 3.7.5, en-core-web-sm==3.7.1, tried to install the 2.3.5 like @nabeeltahirdeveloper mentioned yet got subprocess error, I am looking for an updated fix for the current version

**Comment by ghost** [comment]
but it has this error.
        Traceback (most recent call last):
          File "C:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
            main()
          File "C:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
            return hook(config_settings)
                   ^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\USER\AppData\Local\Temp\pip-build-env-p66g1h5p\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
            return self._get_build_requires(config_settings, requirements=[])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\USER\AppData\Local\Temp\pip-build-env-p66g1h5p\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
            self.run_setup()
          File "C:\Users\USER\AppData\Local\Temp\pip-build-env-p66g1h5p\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
            exec(code, locals())
          File "<string>", line 258, in <module>
          File "<string>", line 195, in setup_package
          File "C:\Users\USER\AppData\Local\Temp\pip-build-env-p66g1h5p\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1154, in cythonize
            cythonize_one(*args)
          File "C:\Users\USER\AppData\Local\Temp\pip-build-env-p66g1h5p\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1321, in cythonize_one
            raise CompileError(None, pyx_file)
        Cython.Compiler.Errors.CompileError: thinc/extra/eg.pyx
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error

      Getting requirements to build wheel did not run successfully.
      exit code: 1

      See above for output.

      note: This error originates from a subprocess, and is likely not a problem with pip.

      [notice] A new release of pip is available: 24.0 -> 24.1.2
      [notice] To update, run: python.exe -m pip install --upgrade pip
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
