### ISSUE TITLE
OSError: [E053] Could not read config file from spaCy configuration

### ISSUE THREAD

**Issue by swapnilbadgujar132** [OmkarPathak/pyresparser#88]
### ERROR Massage :
__
(myenv) projectPath> python scan_resume.py
C:\Users\swapn\AppData\Local\Programs\Python\Python312\myenv\Lib\site-packages\spacy\util.py:918: UserWarning: [W094] Model 'en_training' (0.0.0) specifies an under-constrained spaCy version requirement: >=2.1.4. This can lead to compatibility problems with older versions, or as new spaCy versions are released, because the model may say it's compatible when it's not. Consider changing the "spacy_version" in your meta.json to a version range, with a lower and upper pin. For example: >=3.7.2,<3.8.0
  warnings.warn(warn_msg)
Traceback (most recent call last):
  File "projectPath", line 115, in <module>
    data = ResumeParser('candidate_resume/0cc13072ee09d75591245a3dfc708237.pdf').get_extracted_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "userName\AppData\Local\Programs\Python\Python312\myenv\Lib\site-packages\pyresparser\resume_parser.py", line 21, in __init__
    custom_nlp = spacy.load(os.path.dirname(os.path.abspath(__file__)))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "userName\AppData\Local\Programs\Python\Python312\myenv\Lib\site-packages\spacy\__init__.py", line 51, in load
    return util.load_model(
           ^^^^^^^^^^^^^^^^
  File "userName\AppData\Local\Programs\Python\Python312\myenv\Lib\site-packages\spacy\util.py", line 467, in load_model
    return load_model_from_path(Path(name), **kwargs)  # type: ignore[arg-type]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "userName\AppData\Local\Programs\Python\Python312\myenv\Lib\site-packages\spacy\util.py", line 538, in load_model_from_path
    config = load_config(config_path, overrides=overrides)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "userName\AppData\Local\Programs\Python\Python312\myenv\Lib\site-packages\spacy\util.py", line 714, in load_config
    raise IOError(Errors.E053.format(path=config_path, name="config file"))
### OSError: [E053] Could not read config file from userName\AppData\Local\Programs\Python\Python312\myenv\Lib\site-packages\pyresparser\config.cfg

**Comment by Durvalm** [comment]
same error, anyone fixed it?

**Comment by LTan-101104** [comment]
I got the same error too. 

At first I thought it was about spacy and the en_core_web_sm model version mismatch. After trying different solutions of downgrading and reinstalling on the internet, I still got the exact same issue.
